### ISSUE TITLE
Error Install

### ISSUE THREAD

**Issue by Brissan** [rzakhanov/translation-nova-laravel#1]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires rzakhanov/translation * -> satisfiable by rzakhanov/translation[v1.0.0].
    - rzakhanov/translation v1.0.0 requires laravel/framework ^8.0 -> found laravel/framework[v8.0.0, ..., v8.83.27] but it conflicts with your root composer.json require (^10.10).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require rzakhanov/translation:*" to figure out if any version is installable, or "composer require rzakhanov/translation:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by rzakhanov** [comment]
Package requirements fixed and minimized.

**Comment by rzakhanov** [comment]
Try again please.

**Comment by Brissan** [comment]
it is not possible to try it out since version 1.0.0 has remained, the error has not disappeared

**Comment by huuloc4193** [comment]
same issue
