### ISSUE TITLE
Cannot install on Laravel 10

### ISSUE THREAD

**Issue by janiator** [rzakhanov/translation-nova-laravel#2]
rzakhanov/translation v1.0.0 requires laravel/framework ^8.0 -> found laravel/framework[v8.0.0, ..., v8.83.27] but it conflicts with your root composer.json require (^10.0).

**Comment by rzakhanov** [comment]
Hi. Please share composer.json. It seems error related personal files.

**Comment by rzakhanov** [comment]
Not responded from author
